export const Books = [
  {
    id: 213,
    bookName: "Harry Potter",
    author: "hdhdhdhdjdjkd",
    cost: 200,
    genre: "fantastic",
    conplet: false,
    img: "https://i.pinimg.com/474x/5b/3c/6d/5b3c6d19807386304c503c2c346c9155.jpg ",
  },
  {
    id: 213,
    bookName: "Bride",
    author: "hdhdhdhdjdjkd",
    genre: "Biografic",
    cost: 150,
    conplet: false,
    img: " https://placehold.co/150x150",
  },
  {
    id: 213,
    bookName: "Not in Love",
    author: "hdhdhdhdjdjkd",
    genre: "romantic",
    cost: 465,
    conplet: false,
    img: " https://placehold.co/150x150",
  },
  {
    id: 213,
    bookName: "The Wedding People",
    author: "hdhdhdhdjdjkd",
    genre: "romantic",
    cost: 899,
    conplet: false,
    img: " https://placehold.co/150x150",
  },
  {
    id: 13,
    bookName: "I Hope This Doesn't Find You",
    author: "hdhdhdhdjdjkd",
    genre: "fantastic",
    cost: 224,
    conplet: false,
    img: "https://placehold.co/150x150",
  },
  {
    id: 213,
    bookName: "A Song to Drown Rivers",
    author: "hdhdhdhdjdjkd",
    genre: "fantastic",
    cost: 554,
    conplet: false,
    img: "https://placehold.co/150x150",
  },
];
